# Thin wrapper around the Makefile generated by `rocq makefile` from _CoqProject.
# Usage: make            build everything
#        make Foo.vo     build one file (and its dependencies)
#        make check      build, then check which assumptions lemmas rely on
#        make clean

all: Makefile.rocq
	+$(MAKE) -f Makefile.rocq all

check: all
	sh scripts/check_assumptions.sh

clean: Makefile.rocq
	+$(MAKE) -f Makefile.rocq cleanall
	rm -f Makefile.rocq Makefile.rocq.conf

Makefile.rocq: _CoqProject
	rocq makefile -f _CoqProject -o Makefile.rocq

_CoqProject Makefile: ;

%: Makefile.rocq
	+$(MAKE) -f Makefile.rocq $@

.PHONY: all check clean
