# Thin wrapper around the Makefile generated by `rocq makefile` from _CoqProject.
# Usage: make            build everything
#        make Foo.vo     build one file (and its dependencies)
#        make clean

all: Makefile.rocq
	+$(MAKE) -f Makefile.rocq all

clean: Makefile.rocq
	+$(MAKE) -f Makefile.rocq cleanall
	rm -f Makefile.rocq Makefile.rocq.conf

Makefile.rocq: _CoqProject
	rocq makefile -f _CoqProject -o Makefile.rocq

_CoqProject Makefile: ;

%: Makefile.rocq
	+$(MAKE) -f Makefile.rocq $@

.PHONY: all clean
